sudo: required
services:
    - docker

before_install:
    - docker build -t bsnyder/complex-app -f Dockerfile.dev .

script: 
    - docker run bsnyder/complex-app npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    app: complex-app
    env: "complex-app-env"
    bucket_name: "elasticbeanstalk-us-west-1-064316789315"
    bucket_path: "complex-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
