sudo: required
services:
    - docker

before_install:
    - docker build -t "$DOCKER_ID"/complex-app-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run "$DOCKER_ID"/complex-app-test npm run test -- --coverage

after_success:
    - docker build -t "$DOCKER_ID"/complex-app-client ./client
    - docker build -t "$DOCKER_ID"/complex-app-nginx ./nginx
    - docker build -t "$DOCKER_ID"/complex-app-server ./server
    - docker build -t "$DOCKER_ID"/complex-app-worker ./worker
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
    - docker push "$DOCKER_ID"/complex-app-client
    - docker push "$DOCKER_ID"/complex-app-nginx
    - docker push "$DOCKER_ID"/complex-app-server
    - docker push "$DOCKER_ID"/complex-app-worker
