sudo: required
services:
    - docker

before_install:
    - docker build -t bsnyder/complex-app-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run bsnyder/complex-app-test npm run test -- --coverage

after_success:
    - docker build -t bsnyder/complex-app-client ./client
    - docker build -t bsnyder/complex-app-nginx ./nginx
    - docker build -t bsnyder/complex-app-server ./server
    - docker build -t bsnyder/complex-app-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push bsnyder/complex-app/complex-app-client
    - docker push bsnyder/complex-app/complex-app-nginx
    - docker push bsnyder/complex-app/complex-app-server
    - docker push bsnyder/complex-app/complex-app-worker
